name: warranty_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.1.4
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  intl_utils: ^2.8.7
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
l10n:
  delegates:
    - app_localizations.delegate
  supported_locales:
    - en
    - tr
